version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: backend-challenge
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - '5432:5432'
