version: '3.7'

services:
    database:
        image: postgres
        container_name: database_api
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=API
        volumes:
            - pgdata:/data/postgres

    app:
        build: .
        container_name: places
        restart: always
        ports:
            - 3333:3333

        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database

volumes:
    pgdata:
        driver: local
